version: '3.3'

services:
  nginx:
    image: nginx
    container_name: regions-project
    volumes:
      - '.:/usr/share/nginx/html'
      - ./nginx-conf:/etc/nginx/conf.d
    ports:
    - 8080:80
    environment:
      - NGINX_PORT=80
    restart: unless-stopped
